### ISSUE TITLE
test data files for examples

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/hazdev-geoserve-ws#101]
- layers metadata
- regions query for a point (with all types)
- places query for a point (with type=event)

should be in an "etc" directory, make sure it's mounted for examples in gruntconfig/connect

**Comment by ehunter-usgs** [comment]
Create an "etc" directory and add the three files listed so that they can be used by examples.

**Comment by hasimpson-usgs** [comment]
Evidently I forgot to add/commit them.  They are now there.    Not certain if anyone cares that 2 of them are on a single line.
