### ISSUE TITLE
Update left navigation

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/hazdev-geoserve-ws#138]
Some pages are missing from the left nav, and some don't work.

**Comment by emartinez-usgs** [comment]
Specifically the location.php page is not listed. Additionally, when on the location.php page, the links to endpoint documentation are broken.

**Comment by emartinez-usgs** [comment]
- `True` should be lower case `true`
- Use metadata.inc.php to generate navigation for endpoints (since this can change)
  - This can be done in "_navigation.inc.php"

**Comment by emcwhirter-usgs** [comment]
Do you mean that I should create a location.inc.php to be used by metadata.inc.php?

**Comment by emartinez-usgs** [comment]
Closed by #149
