### ISSUE TITLE
Timezone & Offshore Layer Error

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/hazdev-geoserve-ws#156]
Server commonly responds with a `503 Service Unavailable` when trying to view timezone layer on interactive map (http://earthquake.usgs.gov/ws/geoserve/).

Server error states a memory issue:

```
[Thu Dec 03 14:43:25 2015] [error] [client 192.168.0.2] PHP Fatal error: 
Allowed memory size of 134217728 bytes exhausted (tried to allocate 42269802 bytes)
  in hazdev-geoserve-ws/lib/classes/GeoserveWebService.class.php on line 99
  referer: http://earthquake.usgs.gov/ws/geoserve/
```

This might get resolved as part of #155 if the timezone dataset becomes more coarsely defined (thus smaller). Alternatively we may need a streaming service implementation.

**Comment by ehunter-usgs** [comment]
This also now includes the "offshore" data set.

**Comment by jmfee-usgs** [comment]
These layers have been removed from the "layers" service because of their size..
