### ISSUE TITLE
Undefined Index Error

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/hazdev-geoserve-ws#157]
Server reports an undefined index error on the following pages:
- http://earthquake.usgs.gov/ws/geoserve/layers.php
- http://earthquake.usgs.gov/ws/geoserve/regions.php

Problem appears to be in [layers.php](https://github.com/usgs/hazdev-geoserve-ws/blob/master/src/htdocs/layers.php#L84) and [regions.php](https://github.com/usgs/hazdev-geoserve-ws/blob/master/src/htdocs/regions.php#L84) on or around line 84.

**Comment by jmfee-usgs** [comment]
Appears to have been fixed.
