### ISSUE TITLE
Update Tectonic Summary - NEIC Data

### ISSUE THREAD

**Issue by gsmoczyk** [usgs/hazdev-geoserve-ws#174]
Tectonic summary region boundaries for the Eastern Margin of Australia and New Guinea regions have been updated.  Please push these updates to production when possible.  The file can be found at: /ftp/pub/web/hazdev-geoserve-ws/tectonic/tectonicsummary_neic.dat on the FTP site.

The HVO authoritative region has been updated as well.  The file can be found at: /ftp/pub/web/hazdev-geoserve-ws/auth/authregions.dat on the FTP site.

**Comment by jmfee-usgs** [comment]
Updated in the sciencebase data release, https://www.sciencebase.gov/catalog/item/5a6f547de4b06e28e9caca43 , which is loaded by https://github.com/usgs/hazdev-geoserve-ws/releases/tag/1.5.0
