### ISSUE TITLE
Updated Geoserve data files to test

### ISSUE THREAD

**Issue by gsmoczyk** [usgs/hazdev-geoserve-ws#192]
Geoserve data files can now be downloaded from ScienceBase at: 
[(https://www.sciencebase.gov/catalog/item/5a6f547de4b06e28e9caca43)]

These will replace the versions on the FTP! Please review the format of the changelog.json file to ensure it meets requirements. Please also test loading the updated .dat files into Geoserve. Note that the shape column now needs to be imported using the "ST_GeomFromGeoJSON" constructor rather than the "ST_GeomFromText" constructor. Let me know if there are any issues with the loading process.

**Comment by emartinez-usgs** [comment]
- changelog.json has a validation error. Missing ending quotation on `tectonicsummary_ut`.
- I don't see geonames. Is there licensing issues with this? How are we mean to get this part of the data? Specifically:
  - cities1000.zip
  - US.zip
  - admin1CodesASCII.txt
- Can the tectonic summary zip file be stored as the three component files separately? To be clear, zipped is okay, but one file per zip archive.
- Maybe we store all files either as `.zip` or `.dat` for consistency. I vote `.zip` for storage, each zip file contains a single `.dat` file.
- Can we change the visibility so one does not require a username/password to access the data ?

**Comment by gsmoczyk** [comment]
The changelog.json file error should be eliminated now. I've copied Geonames files that were on the FTP site to ScienceBase. I believe these are created and maintained by Eddie. I've added all of your accounts to have full write access to this folder in ScienceBase so that you can push the Geonames files when they get updated. Each of the files is now individually contained in a .zip. This folder is publicly viewable in ScienceBase now so that should eliminate the username/password overhead... Let me know if I'm missing anything else.

**Comment by emartinez-usgs** [comment]
What is the motivation for swapping to GeoJSON fragments for the data load format? In general I like GeoJSON, but in this case it complicates the data load and impedes adopting this new data set for our standard workflow.

**Comment by emartinez-usgs** [comment]
For reference, here is a quick snippet on how the data loaders could be updated if we stick with GeoJSON:
```
$dbInstaller->run("
  CREATE TEMP TABLE authoritative_text_loader (LIKE authoritative);
  ALTER TABLE authoritative_text_loader ALTER COLUMN shape TYPE TEXT;
");
$dbInstaller->copyFrom('/tmp/authregions.dat', 'authoritative_text_loader',
    array('NULL AS \'\'', 'CSV', 'HEADER'));
$dbInstaller->run("
  INSERT INTO
    authoritative
  (
    SELECT
      id,
      name,
      type,
      priority,
      network,
      ST_SetSRID(ST_GeomFromGeoJSON(shape), 4326) AS shape
    FROM
      authoritative_text_loader
  );
  DROP TABLE IF EXISTS authoritative_text_loader
");
```

**Comment by gsmoczyk** [comment]
The motivation of switching to GeoJSON is largely to allow for better manipulation of coordinate values at the database level. GeoJSON is also a far friendlier standard to geospatial end users than WKT and since this is now on ScienceBase, it seems like a better choice. So the only difference from the previous select statement is the use of the ST_GeomFromGeoJSON geometry constructor rather than using the ST_GeomFromText constructor to populate the shape column, correct?

**Comment by emartinez-usgs** [comment]
It's not quite that simple but we can work with it.

**Comment by gsmoczyk** [comment]
Per our discussion yesterday afternoon, I've added "version" and "download" members to to top level of the JSON file. The "version" at the top level corresponds to the overall Geoserve data update while the "download" member provides the url to retrieve all of the zip files for the entire project. This URL will remain consistent.

**Comment by jmfee-usgs** [comment]
https://github.com/usgs/hazdev-geoserve-ws/releases/tag/1.5.0 and recent updates to the sciencebase data release address these issues https://www.sciencebase.gov/catalog/item/5a6f547de4b06e28e9caca43
