### ISSUE TITLE
Fix typo on places documentation

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/hazdev-geoserve-ws#83]
First sentence: "enpoint" should be "endpoint", "certian" should be "certain".

Double check the rest.

**Comment by emartinez-usgs** [comment]
@hasimpson-usgs : Is there a pull request for this somewhere?

**Comment by hasimpson-usgs** [comment]
Fixed by Pull request 90.  I mistyped the ticket name.

**Comment by emartinez-usgs** [comment]
@jmfee-usgs merged this yesterday.
