### ISSUE TITLE
Add places information to datasets readme

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/hazdev-geoserve-ws#84]

**Comment by jdbrown-USGS** [comment]
- Added readme to geonames dataset can be seen here.

ftp://ftpext.usgs.gov/pub/cr/co/golden/hazards/web/hazdev-geoserve-ws/geonames/

**Comment by jmfee-usgs** [comment]
"where" should be "were", otherwise looks good.

**Comment by jdbrown-USGS** [comment]
Fixed typo.

**Comment by jdbrown-USGS** [comment]
Changed file from .md to .txt.
